username = "Tenyoru"
name = "core"
platform = "x86_64-linux"

[packages]
gvfs = true
tumbler = true
"file-roller" = true
"pipewire.jack" = true
opencode = true
gh = true
openssl = true
imagemagick = true
"notify-desktop" = true
postgresql = true
"dfu-util" = true
chezmoi = true
"platformio-core" = true
"gnome-keyring" = true
"xwayland-satellite" = true
wtype = true
ffmpeg = true
guitarix = true
devenv = true
gnumake = false
unzip = true
just = true
macchina = false
"wf-recorder" = true
obs-studio = true
"wireguard-tools" = true
qpwgraph = true
pavucontrol = true
taskwarrior3 = false
timewarrior = false
jmtpfs = false
exiftool = true
mpd = true
typst = true
mpc = true
blender = true
"ssh-agents" = true
rustup = true
"anki-bin" = true
waybar = true
go = true
fluffychat = true
cloudflared = true
libresprite = true
cheese = true
krita = true
"bitwarden-cli" = true
"telegram-desktop" = true

[stablePackages]
iamb = true
"bambu-studio" = true

[dotfiles]
enable = true
bin = true

[host]
fonts = true
locale = true
audio = true
nix = true
user = true
ssh = true
wayland = true
niri = true
virtualisation = false
clamav = true
docker = true
boot = true
hardware = true
networking = true
programs = true
services = true
syncthing = false
"core-configuration" = true
eid = true
steam = true
power = true
ollama = false
[home]
opencode = true
claude = true
cli-suggar = true
dev = true
zig = true
python = true
whisper = true
git = true
obsidian = false
zathura = true
zen-browser = true
tmux = true
fish = true
neovim = true
ghostty = true
notes = true
noctalia = true
chawan = true
discord = true
jujutsu = false
darkman = false
ayugram = false
spotify = true
gws = true
grok-bot = true