username = "Tenyoru"
name = "core"
platform = "x86_64-linux"

[packages]
thunar = true
gvfs = true
tumbler = true
"thunar-archive-plugin" = true
"thunar-volman" = true
"file-roller" = true
"pipewire.jack" = true
opencode = true
gh = true
openssl = true
imagemagick = true
"notify-desktop" = true
postgresql = true
"dfu-util" = true
"ayugram-desktop" = true
chezmoi = true
"platformio-core" = true
"gnome-keyring" = true
"xwayland-satellite" = true
wtype = true
ffmpeg = true
"yt-dlp" = true
devenv = true
gnumake = true
just = true
macchina = true
"wf-recorder" = true
obs-studio = true
"wireguard-tools" = true
qpwgraph = true
pavucontrol = true
taskwarrior3 = false
timewarrior = false
jmtpfs = true
exiftool = true
mpd = true
typst = true
mpc = true
blender = true
"orca-slicer" = true
"ssh-agents" = true
rustup = true
"anki-bin" = true
waybar = true
go = true
fluffychat = true
cloudflared = true
"proton-pass" = true
libresprite = true
cheese = true
"zed-editor" = true

[stablePackages]
guitarix = true
iamb = true
"bambu-studio" = true

[dotfiles]
enable = true
bin = true

[host]
fonts = true
locale = true
audio = true
nix = true
user = true
ssh = true
wayland = true
virtualisation = false
clamav = true
docker = false
boot = true
hardware = true
networking = true
programs = true
services = true
syncthing = true
"core-configuration" = true
tailscale = false
[home]
opencode = true
claude = true
cli-suggar = true
dev = true
zig = true
python = true
whisper = true
git = true
obsidian = true
zathura = true
zen-browser = true
spotify = true
tmux = true
fish = true
neovim = true
mako = true
ghostty = true
niri = true
noctalia = true
chawan = true
discord = false
jujutsu = true
darkman = false
prismlauncher = false
