{mylib, ...}: {
  imports = mylib.getHomeModules [
    "opencode"
    "claude"
    "cli-suggar"
    "dev"
    "python"
    "whisper"
    "anyrun"
    "git"
    "obsidian"
    "zathura"
    "zen-browser"
    "tmux"
    "fish"
    "neovim"
    "mako"
    "ghostty"
    "niri"
    "spotify"
    ({pkgs, inputs, ...}: {
      home.packages = with pkgs; [
        pipewire.jack
        opencode
        openssl
        imagemagick
        notify-desktop
        inputs.stable.legacyPackages.${pkgs.stdenv.hostPlatform.system}.guitarix
        postgresql
        dfu-util
        ayugram-desktop
        chezmoi
        zig
        inputs.stable.legacyPackages.${pkgs.stdenv.hostPlatform.system}.iamb
        discord
        platformio-core
        gnome-keyring
        xwayland-satellite
        wtype
        ffmpeg
        yt-dlp
        tor-browser
        devenv
        gnumake
        just
        macchina
        wf-recorder
        wireguard-tools
        qpwgraph
        pavucontrol
        taskwarrior3
        timewarrior
        jmtpfs
        exiftool
        veracrypt
        hugo
        dart-sass
        mpd
        typst
        mpc
        blender
        bambu-studio
        ssh-agents
        rustup
        anki-bin
        waybar
        go
        fluffychat
        cloudflared
        proton-pass
      ];
    })
  ];
}
