{mylib, ...}: {
  imports = mylib.getHomeModules [
    "claude"
    "cli-suggar"
    "dev"
    "obs"
    "anyrun"
    "git"
    "zathura"
    "qutebrowser"
    "tmux"
    "fish"
    "neovim"
    "mako"
    "ghostty"
    "niri"
    "spotify"
    ({pkgs, inputs, ...}: {
      home.packages = with pkgs; [
        pipewire.jack
        openssl
        imagemagick
        notify-desktop
        inputs.stable.legacyPackages.${pkgs.stdenv.hostPlatform.system}.guitarix
        postgresql
        dfu-util
        ayugram-desktop
        chezmoi
        zig
        iamb
        discord
        platformio-core
        gnome-keyring
        xwayland-satellite
        python3
        tor-browser
        devenv
        gnumake
        just
        macchina
        wf-recorder
        wireguard-tools
        qpwgraph
        pavucontrol
        taskwarrior3
        timewarrior
        jmtpfs
        exiftool
        veracrypt
        uv
        hugo
        dart-sass
        gdal
        mpd
        typst
        mpc
        blender
        freecad
        bambu-studio
        ssh-agents
        rustup
        anki-bin
        waybar
        go
        fluffychat
        cloudflared
        obsidian
        proton-pass
      ];
    })
  ];
}
